version: "3"

volumes:
  crm_local_postgres_data: {}
  crm_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./docker/django/local/Dockerfile
    image: crm_local_django
    container_name: crm_local_django
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./backend/.envs/.local/.django
      - ./backend/.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: crm_production_postgres
    container_name: crm_local_postgres
    volumes:
      - crm_local_postgres_data:/var/lib/postgresql/data
      - crm_local_postgres_data_backups:/backups
    env_file:
      - ./backend/.envs/.local/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: crm_local_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: crm_local_redis

  celeryworker:
    <<: *django
    image: crm_local_celeryworker
    container_name: crm_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: crm_local_celerybeat
    container_name: crm_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: crm_local_flower
    container_name: crm_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
