#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

cd backend

python manage.py migrate
python manage.py collectstatic --noinput
python manage.py create_groups

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
