# Generated by Django 4.2.3 on 2023-07-19 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, verbose_name="Наименования")),
                ("image", models.ImageField(blank=True, null=True, upload_to="text-blocks/", verbose_name="Картинка")),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="companies.company", verbose_name="Компания"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PDF Blocks",
            },
        ),
    ]
