# Generated by Django 4.2.3 on 2023-07-31 08:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdfblock",
            name="text",
            field=ckeditor.fields.RichTextField(verbose_name="Текст"),
        ),
    ]
