# Generated by Django 4.2.3 on 2023-07-20 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="business_card",
            field=models.TextField(blank=True, verbose_name="Визитка"),
        ),
        migrations.AlterField(
            model_name="company",
            name="signature_image",
            field=models.ImageField(
                blank=True, default="", upload_to="company-signatures/", verbose_name="Подпись"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="companymember",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="companies.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AlterField(
            model_name="companymember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="companytype",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_types",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="companies.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deals",
                to="companies.customer",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals",
                to="companies.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="companies.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="companies.product",
                verbose_name="Товар",
            ),
        ),
    ]
