# Generated by Django 4.2.3 on 2023-07-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_company_business_card_alter_company_signature_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyproductlink",
            name="is_valid",
            field=models.BooleanField(default=True, verbose_name="Функционирующий"),
        ),
    ]
