# Generated by Django 4.2.3 on 2023-07-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_companyproductlink_is_valid"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=70, verbose_name="Ключ")),
                ("value", models.CharField(max_length=70, verbose_name="Значение")),
            ],
            options={
                "verbose_name_plural": "Product Translations",
            },
        ),
    ]
