# Generated by Django 4.2.3 on 2023-07-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_producttranslation"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="offer_template",
            field=models.CharField(
                choices=[("commercial-offers/1.html", "Шаблон коммерческого предложения #1")],
                default="commercial-offers/1.html",
                max_length=150,
                verbose_name="Шаблон для коммерческого предложения",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="price_template",
            field=models.CharField(
                choices=[("price-lists/1.docx", "Шаблон прайс-листа #1")],
                default="price-lists/1.docx",
                max_length=150,
                verbose_name="Шаблон для прайс-листа",
            ),
        ),
    ]
