# Generated by Django 4.2.3 on 2023-07-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0005_company_offer_template_company_price_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="price_template",
            field=models.CharField(
                choices=[("price-lists/1.html", "Шаблон прайс-листа #1")],
                default="price-lists/1.html",
                max_length=150,
                verbose_name="Шаблон для прайс-листа",
            ),
        ),
    ]
