# Generated by Django 4.2.3 on 2023-08-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0007_alter_company_business_card"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["pid"], name="companies_p_pid_e12c22_idx"),
        ),
    ]
